export const AI_PROVIDER_CONFIGURATION_REPOSITORY = Symbol("AI_PROVIDER_CONFIGURATION_REPOSITORY");
export const AI_PROMPT_TEMPLATE_REPOSITORY = Symbol("AI_PROMPT_TEMPLATE_REPOSITORY");
export const AI_CONVERSATION_REPOSITORY = Symbol("AI_CONVERSATION_REPOSITORY");
export const AI_USAGE_RECORD_REPOSITORY = Symbol("AI_USAGE_RECORD_REPOSITORY");
export const AI_AUDIT_REPOSITORY = Symbol("AI_AUDIT_REPOSITORY");
export const AI_PROVIDER_REGISTRY = Symbol("AI_PROVIDER_REGISTRY");
