export const SERVICE_REPOSITORY = Symbol("SERVICE_REPOSITORY");
export const ENVIRONMENT_REPOSITORY = Symbol("ENVIRONMENT_REPOSITORY");
export const DEPENDENCY_REPOSITORY = Symbol("DEPENDENCY_REPOSITORY");
export const DEPLOYMENT_REPOSITORY = Symbol("DEPLOYMENT_REPOSITORY");
export const HEALTH_CHECK_REPOSITORY = Symbol("HEALTH_CHECK_REPOSITORY");
export const HEALTH_RESULT_REPOSITORY = Symbol("HEALTH_RESULT_REPOSITORY");
export const HEALTH_EVALUATION_REPOSITORY = Symbol("HEALTH_EVALUATION_REPOSITORY");
