export const SERVICE_REPOSITORY = Symbol("SERVICE_REPOSITORY");
export const ENVIRONMENT_REPOSITORY = Symbol("ENVIRONMENT_REPOSITORY");
export const DEPENDENCY_REPOSITORY = Symbol("DEPENDENCY_REPOSITORY");
export const DEPLOYMENT_REPOSITORY = Symbol("DEPLOYMENT_REPOSITORY");
