export const INCIDENT_REPOSITORY = Symbol("INCIDENT_REPOSITORY");
export const INCIDENT_COMMENT_REPOSITORY = Symbol("INCIDENT_COMMENT_REPOSITORY");
export const INCIDENT_TIMELINE_REPOSITORY = Symbol("INCIDENT_TIMELINE_REPOSITORY");
export const INCIDENT_MENTION_REPOSITORY = Symbol("INCIDENT_MENTION_REPOSITORY");
export const INCIDENT_ATTACHMENT_REPOSITORY = Symbol("INCIDENT_ATTACHMENT_REPOSITORY");
export const INCIDENT_ATTACHMENT_STORAGE = Symbol("INCIDENT_ATTACHMENT_STORAGE");
