import type { PermissionKey, UserRole } from "@plusops/contracts";

export const SYSTEM_ROLES = {
  ADMIN: "admin",
  ENGINEERING_MANAGER: "engineering_manager",
  DEVELOPER: "developer",
  QA_ENGINEER: "qa_engineer",
  VIEWER: "viewer"
} as const satisfies Record<string, UserRole>;

export const SYSTEM_PERMISSIONS = {
  PLATFORM_ADMIN: "platform:admin",
  USERS_READ: "users:read",
  USERS_MANAGE: "users:manage",
  ROLES_MANAGE: "roles:manage",
  PROFILE_READ: "profile:read",
  PROFILE_UPDATE: "profile:update",
  SESSIONS_MANAGE_OWN: "sessions:manage-own",
  SERVICE_VIEW: "service:view",
  SERVICE_CREATE: "service:create",
  SERVICE_UPDATE: "service:update",
  SERVICE_ARCHIVE: "service:archive",
  SERVICE_MANAGE: "service:manage",
  HEALTH_VIEW: "health:view",
  HEALTH_RUN: "health:run",
  HEALTH_MANAGE: "health:manage",
  SERVICES_READ: "services:read",
  SERVICES_WRITE: "services:write",
  INCIDENTS_READ: "incidents:read",
  INCIDENTS_WRITE: "incidents:write",
  INCIDENTS_MANAGE: "incidents:manage"
} as const satisfies Record<string, PermissionKey>;

export const ROLE_PERMISSION_MATRIX = {
  admin: Object.values(SYSTEM_PERMISSIONS),
  engineering_manager: [
    SYSTEM_PERMISSIONS.USERS_READ,
    SYSTEM_PERMISSIONS.PROFILE_READ,
    SYSTEM_PERMISSIONS.PROFILE_UPDATE,
    SYSTEM_PERMISSIONS.SESSIONS_MANAGE_OWN,
    SYSTEM_PERMISSIONS.SERVICE_VIEW,
    SYSTEM_PERMISSIONS.SERVICE_CREATE,
    SYSTEM_PERMISSIONS.SERVICE_UPDATE,
    SYSTEM_PERMISSIONS.SERVICE_ARCHIVE,
    SYSTEM_PERMISSIONS.SERVICE_MANAGE,
    SYSTEM_PERMISSIONS.HEALTH_VIEW,
    SYSTEM_PERMISSIONS.HEALTH_RUN,
    SYSTEM_PERMISSIONS.HEALTH_MANAGE,
    SYSTEM_PERMISSIONS.SERVICES_READ,
    SYSTEM_PERMISSIONS.SERVICES_WRITE,
    SYSTEM_PERMISSIONS.INCIDENTS_READ,
    SYSTEM_PERMISSIONS.INCIDENTS_WRITE,
    SYSTEM_PERMISSIONS.INCIDENTS_MANAGE
  ],
  developer: [
    SYSTEM_PERMISSIONS.PROFILE_READ,
    SYSTEM_PERMISSIONS.PROFILE_UPDATE,
    SYSTEM_PERMISSIONS.SESSIONS_MANAGE_OWN,
    SYSTEM_PERMISSIONS.SERVICE_VIEW,
    SYSTEM_PERMISSIONS.SERVICE_CREATE,
    SYSTEM_PERMISSIONS.SERVICE_UPDATE,
    SYSTEM_PERMISSIONS.HEALTH_VIEW,
    SYSTEM_PERMISSIONS.HEALTH_RUN,
    SYSTEM_PERMISSIONS.SERVICES_READ,
    SYSTEM_PERMISSIONS.SERVICES_WRITE,
    SYSTEM_PERMISSIONS.INCIDENTS_READ,
    SYSTEM_PERMISSIONS.INCIDENTS_WRITE
  ],
  qa_engineer: [
    SYSTEM_PERMISSIONS.PROFILE_READ,
    SYSTEM_PERMISSIONS.PROFILE_UPDATE,
    SYSTEM_PERMISSIONS.SESSIONS_MANAGE_OWN,
    SYSTEM_PERMISSIONS.SERVICE_VIEW,
    SYSTEM_PERMISSIONS.SERVICE_UPDATE,
    SYSTEM_PERMISSIONS.HEALTH_VIEW,
    SYSTEM_PERMISSIONS.SERVICES_READ,
    SYSTEM_PERMISSIONS.INCIDENTS_READ,
    SYSTEM_PERMISSIONS.INCIDENTS_WRITE
  ],
  viewer: [
    SYSTEM_PERMISSIONS.PROFILE_READ,
    SYSTEM_PERMISSIONS.PROFILE_UPDATE,
    SYSTEM_PERMISSIONS.SESSIONS_MANAGE_OWN,
    SYSTEM_PERMISSIONS.SERVICE_VIEW,
    SYSTEM_PERMISSIONS.HEALTH_VIEW,
    SYSTEM_PERMISSIONS.SERVICES_READ,
    SYSTEM_PERMISSIONS.INCIDENTS_READ
  ]
} as const satisfies Record<UserRole, readonly PermissionKey[]>;
