export const AUTH_USER_REPOSITORY = Symbol("AUTH_USER_REPOSITORY");
export const AUTH_SESSION_REPOSITORY = Symbol("AUTH_SESSION_REPOSITORY");
export const AUTH_ONE_TIME_TOKEN_REPOSITORY = Symbol("AUTH_ONE_TIME_TOKEN_REPOSITORY");
export const AUTH_PASSWORD_HASHER = Symbol("AUTH_PASSWORD_HASHER");
export const AUTH_TOKEN_SERVICE = Symbol("AUTH_TOKEN_SERVICE");
export const AUTH_AUDIT_LOG = Symbol("AUTH_AUDIT_LOG");
export const AUTH_CLOCK = Symbol("AUTH_CLOCK");
